import * as LOGICAL_VALIDATORS from './logical'
import * as NUMBER_VALIDATORS from './number'
import * as STRING_VALIDATORS from './string'
import * as ARRAY_VALIDATORS from './array'
import * as BOOLEAN_VALIDATORS from './boolean'
import * as EQUALITY_VALIDATORS from './equality'
import * as OBJECT_VALIDATORS from './object'
import * as MISCELLANEOUS_VALIDATORS from './miscellaneous'
import * as DATE_VALIDATORS from './date'
import * as URL_VALIDATORS from './url'

export const VALIDATORS = {
  ...LOGICAL_VALIDATORS,
  ...NUMBER_VALIDATORS,
  ...STRING_VALIDATORS,
  ...ARRAY_VALIDATORS,
  ...BOOLEAN_VALIDATORS,
  ...EQUALITY_VALIDATORS,
  ...OBJECT_VALIDATORS,
  ...MISCELLANEOUS_VALIDATORS,
  ...DATE_VALIDATORS,
  ...URL_VALIDATORS,
}

export {
  LOGICAL_VALIDATORS,
  NUMBER_VALIDATORS,
  STRING_VALIDATORS,
  ARRAY_VALIDATORS,
  BOOLEAN_VALIDATORS,
  EQUALITY_VALIDATORS,
  OBJECT_VALIDATORS,
  MISCELLANEOUS_VALIDATORS,
  DATE_VALIDATORS,
  URL_VALIDATORS,
}
